apiVersion: v1
kind: Secret
metadata:
  name: conexao-solidaria-api-secret
  namespace: conexao-solidaria
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=conexao_solidaria;Username=conexao-solidaria;Password=sua_senha_aqui
  JwtSettings__Secret: troque-esta-chave-por-uma-chave-com-pelo-menos-32-caracteres
  RabbitMqSettings__Password: sua_senha_aqui