apiVersion: apps/v1
kind: Deployment
metadata:
  name: doacoes-worker
  namespace: conexao-solidaria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doacoes-worker
  template:
    metadata:
      labels:
        app: doacoes-worker
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres 5432; do
                echo "Aguardando Postgres..."
                sleep 3
              done
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Aguardando RabbitMQ..."
                sleep 3
              done
      containers:
        - name: doacoes-worker
          image: doacoes-worker:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: doacoes-worker-config
            - secretRef:
                name: doacoes-worker-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi