apiVersion: v1
kind: Secret
metadata:
  name: doacoes-worker-secret
  namespace: conexao-solidaria
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=conexao_solidaria;Username=conexao-solidaria;Password=sua_senha_aqui
  RabbitMqSettings__Password: sua_senha_aqui