@ConexaoSolidaria.API_HostAddress = http://localhost:5082

POST {{ConexaoSolidaria.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@conexaosolidaria.com.br",
  "senha": "Admin@123"
}

###
