apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: conexao-solidaria
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: conexao-solidaria
  RABBITMQ_DEFAULT_PASS: sua_senha_aqui
  RABBITMQ_DEFAULT_VHOST: /