// <auto-generated />
using System;
using ConexaoSolidaria.Infrastructure.Doacoes.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConexaoSolidaria.Infrastructure.Doacoes.Persistence.Migrations
{
    [DbContext(typeof(DoacaoDbContext))]
    [Migration("20260927124944_MigrationInitialDoacao")]
    partial class MigrationInitialDoacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("doacao")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConexaoSolidaria.Domain.Doacoes.Entities.Doacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("IdCampanha")
                        .HasColumnType("uuid")
                        .HasColumnName("id_campanha");

                    b.Property<Guid>("IdDoador")
                        .HasColumnType("uuid")
                        .HasColumnName("id_doador");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorDoacao")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_doacao");

                    b.HasKey("Id");

                    b.HasIndex("IdCampanha")
                        .HasDatabaseName("ix_doacoes_id_campanha");

                    b.HasIndex("IdDoador")
                        .HasDatabaseName("ix_doacoes_id_doador");

                    b.ToTable("doacoes", "doacao");
                });

            modelBuilder.Entity("ConexaoSolidaria.Infrastructure.Doacoes.Persistence.DoacaoProcessada", b =>
                {
                    b.Property<Guid>("IdDoacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_doacao");

                    b.Property<DateTime>("ProcessadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processada_em");

                    b.HasKey("IdDoacao");

                    b.ToTable("doacoes_processadas", "doacao");
                });
#pragma warning restore 612, 618
        }
    }
}
