apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: conexao-solidaria
type: Opaque
stringData:
  POSTGRES_USER: conexao-solidaria
  POSTGRES_PASSWORD: sua_senha_aqui
  POSTGRES_DB: conexao_solidaria